apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: phwo6t5nq-go-gitops
  description: This is GitOps manifest for phwo6t5nq-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=phwo6t5nq-go
    backstage.io/kubernetes-id: phwo6t5nq-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: phwo6t5nq-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:phwo6t5nq-go
