apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: phwo6t5nq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: phwo6t5nq-go 
  name: phwo6t5nq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: phwo6t5nq-go 
